## clock topic --> nice practice to add clock topic
- ros_topic_name: "/clock"   ## from ros2 topic list
  gz_topic_name: "/clock"    ## gazebo topic
  ros_type_name: "rosgraph_msgs/msg/Clock"    ## type of topics 
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS          ## ROS_TO_GZ OR GZ_TO_ROS OR BIDIRECTIONAL

## Only if gz topic does not co relate with ros2 topic then can be given by ourself 

## state publisher topic
- ros_topic_name: "/joint_states"
  gz_topic_name: "/world/empty/model/my_robot/joint_state"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS

## tf topic
- ros_topic_name: "/tf"
  gz_topic_name: "/model/my_robot/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS

- ros_topic_name: "/cmd_vel"   ## if does not exist just name if
  gz_topic_name: "/model/my_robot/cmd_vel"
  ros_type_name: "geometry_msgs/msg/Twist"
  gz_type_name: "gz.msgs.Twist"
  direction: ROS_TO_GZ   ## publishing from ros

## camear sensor topic bridge
- ros_topic_name: "/camera/camera_info"
  gz_topic_name: "/camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

## image topic 
- ros_topic_name: "/camera/image_raw"
  gz_topic_name: "/camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

- ros_topic_name: "/scan"
  gz_topic_name: "/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# # - ros_topic_name: "/scan"
# #   gz_topic_name: "/world/empty_world/model/my_robot/link/lidar_link/sensor/lidar_sensor/scan"
# #   ros_type_name: "sensor_msgs/msg/LaserScan"
# #   gz_type_name: "gz.msgs.LaserScan"
# #   direction: GZ_TO_ROS


# # this is self written --> many mistake
# # - ros_topic_name: "/lidar/points"
# #   gz_topic_name: "/lidar/points"
# #   ros_type_name: "sensor_msgs/msg/PointCloud2"
# #   gz_type_name: "gz.msgs.PointCloudPacked"
# #   direction: GZ_TO_ROS


# # ## This are bridges of robotic arm  
# # - ros_topic_name: "/joint0/cmd_pos"   ## if does not exist just name if
# #   gz_topic_name: "/model/my_robot/joint/base_forearm_joint/0/cmd_pos"
# #   ros_type_name: "std_msgs/msg/Float64"
# #   gz_type_name: "gz.msgs.Double"
# #   direction: ROS_TO_GZ 

# # - ros_topic_name: "/joint1/cmd_pos"   ## if does not exist just name if
# #   gz_topic_name: "/model/my_robot/joint/forearm_hand_joint/0/cmd_pos"
# #   ros_type_name: "std_msgs/msg/Float64"
# #   gz_type_name: "gz.msgs.Double"
# #   direction: ROS_TO_GZ 